/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface MenuItem { 
    id?: string;
    fullName: string;
    shortName: string;
    price?: number;
    category: MenuItem.CategoryEnum;
    image: string;
}
export namespace MenuItem {
    export type CategoryEnum = 'STARTER' | 'MAIN' | 'DESSERT' | 'BEVERAGE';
    export const CategoryEnum = {
        STARTER: 'STARTER' as CategoryEnum,
        MAIN: 'MAIN' as CategoryEnum,
        DESSERT: 'DESSERT' as CategoryEnum,
        BEVERAGE: 'BEVERAGE' as CategoryEnum
    };
}